DROP TABLE  DEV_BATCH_STEP_EXECUTION_CONTEXT;
DROP TABLE  DEV_BATCH_JOB_EXECUTION_CONTEXT;
DROP TABLE  DEV_BATCH_STEP_EXECUTION;
DROP TABLE  DEV_BATCH_JOB_EXECUTION_PARAMS;
DROP TABLE  DEV_BATCH_JOB_EXECUTION;
DROP TABLE  DEV_BATCH_JOB_INSTANCE;

DROP SEQUENCE  DEV_BATCH_STEP_EXECUTION_SEQ;
DROP SEQUENCE  DEV_BATCH_JOB_EXECUTION_SEQ;
DROP SEQUENCE  DEV_BATCH_JOB_SEQ;
