sap:
  hana:
    datasource:
      hikari:
        jdbc-url: jdbc:sap://localhost:30017/?currentschema=SAPHANABATCH
        username: NILESH
        password: passSap01
        maximum-pool-size: 20
spring:
  main:
    allow-bean-definition-overriding: true
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
saphana:
  create:
    script: sqlQueries/create-tables-in-sap.sql
  drop:
    script: sqlQueries/drop-tables-in-sap.sql
  run:
    script: true


